name: Kernel CI (SM-J320FN)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4.1.5

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1 ccache
        sudo git clone --depth 1 --branch android-7.1.2_r37 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 /opt/toolchains/arm-eabi-4.8/
    - name: Building Kernel
      run: |
        export KBUILD_BUILD_USER=notnoelchannel
        export KBUILD_BUILD_HOST=unlegacy-devices
        make -j4 j3xnlte_defconfig
        make -j16
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/Image /home/runner/work/output/zImage
    - name: Uploading Output
      uses: actions/upload-artifact@v4
      with:
        name: zImage
        path: /home/runner/work/output/zImage
